DROP DATABASE baseball;

CREATE DATABASE baseball;

USE baseball;

CREATE TABLE Team (
    TName VARCHAR(255) PRIMARY KEY,
    Captain VARCHAR(255)
);

CREATE TABLE Player (
    SID VARCHAR(255) PRIMARY KEY,
    PName VARCHAR(255),
    Dept VARCHAR(255),
    Grade VARCHAR(255),
    Sex VARCHAR(255),
    JerNum INT,
    Team VARCHAR(255),
    FOREIGN KEY(Team) REFERENCES Team(TName)
);

CREATE TABLE Manager(
    SID VARCHAR(255) PRIMARY KEY,
    PName VARCHAR(255),
    Dept VARCHAR(255),
    Grade VARCHAR(255),
    Sex VARCHAR(255),
    Team VARCHAR(255),
    FOREIGN KEY(Team) REFERENCES Team(TName)
);

CREATE TABLE GAME(
    GID INT PRIMARY KEY,
    GameDate DATE,
    HomeTeam VARCHAR(255),
    HomeScore INT,
    AwayTeam VARCHAR(255),
    AwayScore INT,
    FOREIGN KEY(HomeTeam) REFERENCES Team(TName),
    FOREIGN KEY(AwayTeam) REFERENCES Team(TName)
);

CREATE TABLE HitRecord(
    GID INT,
    PAID INT,
    Result VARCHAR(255),
    Pitcher VARCHAR(255),
    Hitter VARCHAR(255),
    FOREIGN KEY(GID) REFERENCES Game(GID),
    FOREIGN KEY(Pitcher) REFERENCES PLAYER(SID),
    FOREIGN KEY(Hitter) REFERENCES PLAYER(SID)
);

CREATE TABLE Relative(
    SID VARCHAR(255),
    Relation VARCHAR(255),
    Phone VARCHAR(255),
    Name VARCHAR(255),
    FOREIGN KEY(SID) REFERENCES Player(SID)
);

CREATE TABLE Attendance(
    GID INT,
    SID VARCHAR(255),
    Position VARCHAR(255),
    FOREIGN KEY(GID) REFERENCES Game(GID),
    FOREIGN KEY(SID) REFERENCES Player(SID)
);

CREATE TABLE CanPosition(
    SID VARCHAR(255),
    Position VARCHAR(255),
    FOREIGN KEY(SID) REFERENCES Player(SID)
);